### ISSUE TITLE
Failing script phases, while archiving, do not fail the task.

### ISSUE THREAD

**Issue by alloy** [lukeredpath/xcodebuild-rb#2]
When a script build phase fails during normal builds, the output reflects that with: `BUILD FAILED`. However, if you run the same scheme, but archive instead of a normal build, the output will **not** reflect the failing script phase:

```
** ARCHIVE SUCCEEDED **


The following build commands failed:
    PhaseScriptExecution "Run Script" DerivedData/FailingExampleProject/ArchiveIntermediates/FailingExampleProject/IntermediateBuildFilesPath/FailingExampleProject.build/Release-iphoneos/FailingExampleProject.build/Script-51CEAC3F14DAC95400C8B410.sh
(1 failure)
```

(This output is from a simple [sample](https://github.com/Fingertips/xcodebuild-rb/tree/failing-example) I added to the repo.)

**Comment by lukeredpath** [comment]
Interesting. My initial feeling is that we should be introspecting the resulting Build object that we build up in build_reporting.rb for a more definitive answer to whether or not xcodebuild was successful instead of relying on just the exit code. Thanks for the sample, that will help fix this.
